### ISSUE TITLE
Time command

### ISSUE THREAD

**Issue by kevintongg** [IanMitchell/ARX-7#116]
Suggestion of returning output of "Invalid time format" or something since it is based on the tz database.

.time dsadsad returns "Invalid time zone. Please refer to the tz database." or something

Only because .time (any input other than a valid tz database input just returns GMT+0. 

:thumbsup:

**Comment by IanMitchell** [comment]
@Kyhz you want to take a crack at this, or should I?

**Comment by IanMitchell** [comment]
Actually, you should do this @kevintongg ;)

**Comment by kevintongg** [comment]
Wow, @IanMitchell! Soon™.

**Comment by IanMitchell** [comment]
TOO LONG, DIUM

**Comment by kevintongg** [comment]
Soon™
