### ISSUE TITLE
Choose Random Anime to Watch

### ISSUE THREAD

**Issue by BlueCrystal** [IanMitchell/ARX-7#120]
Basically add the feature to .register <service> <username> where service is either MyAnimeList or Hummingbird and username is your site username, and you can do a .choose with no options or anything and it'll choose a show from your currently watching to watch. I guess you could also just add a new command altogether and call it .anime and do .anime cw for a currently watching show to be picking or .anime ptw and have it pick something from your plan to watch, etc.

**Comment by BlueCrystal** [comment]
As requested: <Desch> http://www.smashingmagazine.com/2015/04/web-scraping-with-nodejs/ put that link in the github issue for me

**Comment by IanMitchell** [comment]
Might make it `.watch <mal>`. Definitely something I'll look into; Might not do hummingbird yet because I don't know a lot of people who use it.

**Comment by BlueCrystal** [comment]
I use it bro.

**Comment by IanMitchell** [comment]
WELL THEN

**Comment by kunaldes** [comment]
Hummingbird has an API... it'd probably be easier.

**Comment by kunaldes** [comment]
example: http://hummingbird.me/api/v1/users/jukez/library?status=currently-watching

**Comment by IanMitchell** [comment]
APIs would be a little obtuse to work with... I think keeping it as a `.c 1-26` is the best option.
