### ISSUE TITLE
Include time in YT plugin

### ISSUE THREAD

**Issue by kevintongg** [IanMitchell/ARX-7#126]
Include time and views on YouTube search function

**Comment by IanMitchell** [comment]
thx

**Comment by IanMitchell** [comment]
Alright, so as part of this I'm gonna have to submit a PR to moment.js. Time to get sidetracked

**Comment by IanMitchell** [comment]
Whoops, left in the text despite the value not being passed

**Comment by IanMitchell** [comment]
Command removed
