### ISSUE TITLE
Weather Support

### ISSUE THREAD

**Issue by Velvetine** [IanMitchell/ARX-7#128]
You think it'd be possible to implement weather support?
EXAMPLE: ".w San Jose" would output the current weather conditions for San Jose.
Another idea would to have state/province support to differentiate between cities like Lansing, Michigan and Lansing, Illinois.

**Comment by kunaldes** [comment]
This kind of conflicts with the rizon Internets bot

**Comment by IanMitchell** [comment]
Yeah, I'd rather not implement this
