### ISSUE TITLE
When .done is executed, a nickflash should be performed

### ISSUE THREAD

**Issue by BlueCrystal** [IanMitchell/ARX-7#134]
So when the .done command is performed, it should nickflash the person it's at next (in the staff channel, for example). So lets say I do a .done command for like, timing, and you are the typesetter. The output should have something like "Timing marked as complete. Now waiting on Desch for typesetting." or something like that.

**Comment by Fyurie** [comment]
I can get behind this for the .done command.

My only aversion is using it in the blame command, at least yet, because it can encourage witch-hunting, and that's shitty behaviour.

**Comment by BlueCrystal** [comment]
At least with the blame command, it should be optional in the config.

**Comment by IanMitchell** [comment]
Actually, this is a lot easier now. I can pass an extra parameter to the Blame formatter (default value of false) to display names instead of positions.
