### ISSUE TITLE
Showtime Semantics

### ISSUE THREAD

**Issue by Velvetine** [IanMitchell/ARX-7#135]
There are some concerns I'd like to voice about Showtimes' choice of wording for certain positions.
1. Regarding timing, I suggest changing the notation from "TI" to "TM". The former makes it sound like a show is stuck at some rapper. Also, the latter is what ServrheV5 uses.
2. Right now, when you use .blame for a certain show, it may output something like "XXXX is at Encoder" or "XXXX is at Translation Check." If I may, I would also like to suggest modifying it such that it outputs something like "XXX is at Encoding" or "XXXX is at Translation Checking." This helps maintain better wording.

Okay, that's it.

**Comment by IanMitchell** [comment]
https://www.youtube.com/watch?v=koVHN6eO4Xg

**Comment by IanMitchell** [comment]
As a note, the Timer change will occur in ianmitchell/showtimes instead of this repository

**Comment by Fyurie** [comment]
The points are fair. These aesthetic changes are worthwhile.

(though maybe instead of fully posting translation checking, maybe TLC instead?)

**Comment by Velvetine** [comment]
I was considering putting that in, @Fyurie but I thought it would've been redundant since it already says TLC in the brackets.

**Comment by Fyurie** [comment]
Yeah, I just thought about that. Maybe just leave that alone then. Might look redundant otherwise. :x

**Comment by IanMitchell** [comment]
It'd be easier to leave it alone; If you guys really want that, it'd be better to open a dedicated issue, so I can track them separately (it wouldn't make it as part of this change)

**Comment by Fyurie** [comment]
Yeah, we probably won't bother chasing it further, seems like this is already the best option.

**Comment by IanMitchell** [comment]
Fixed the first part; the second will be handled in the other issue
