### ISSUE TITLE
.blame usage feedback

### ISSUE THREAD

**Issue by Fyurie** [IanMitchell/ARX-7#137]
I'm seeing a lot of people join IRC who don't know how to showtimes (they're literally just typing .blame and nothing else).

Can you have Belfiore reply with an error if a show isn't specified? Maybe something along the lines of "Show not specified, please enter a valid show title." or something along those lines. Makes it a little more foolproof.

thx bb

**Comment by Fyurie** [comment]
Okay no for real watching people join, do .blame, get mad, and leave, while being funny after the xxth time, makes me really doubt humanity.

**Comment by IanMitchell** [comment]
LOL. Yeah, I'll do a quick patch
