### ISSUE TITLE
Stalledat command

### ISSUE THREAD

**Issue by llyyr** [IanMitchell/ARX-7#138]
Exactly what it says on the tin, make a stalledat command so we have a reason to blame Fyurie.

**Comment by IanMitchell** [comment]
Not sure @fyurie wants this - it sounds like he'd rather the position be listed than the crew.

**Comment by Fyurie** [comment]
I'd prefer something like a staff-only command for this, so someone can log on and do .atme or something like that, and see what was still at them/got to them while they were gone, instead of having to .blame lots of shows, your choice of command name though.

**Comment by IanMitchell** [comment]
Two thoughts - 

1. `.stalledat <user>` where user is optional; if user is undefined, whoever issued the command is set as the user.
2. I hate "stalledat". What are some other ways we can phrase this? Since Servrhe uses it, I'll probably set "stalledat" as an alias, but I'd prefer to name the command something else

**Comment by tabaha** [comment]
Maybe .atme?

**Comment by Fyurie** [comment]
Yeah, I suggested .atme a while back.

**Comment by IanMitchell** [comment]
Hm, it's better... I'd prefer if it was just one word though. ".stalling" could maybe work, but the implication you're stalling vs working is still somewhat distasteful. Maybe ".tasks"?

**Comment by Fyurie** [comment]
Mhm, that's why I didn't like stalledat. atme felt like it did the job because someone can just log into staff and type ".atme" and see what their work for the day is. It seemed like a pretty robust solution.

**Comment by IanMitchell** [comment]
> Fyurie:	wait
> Fyurie:	.todo
> Hana:	^
> Fyurie:	Desch I have a winner
