### ISSUE TITLE
Doing .blame <show name> should return results whether the show name is capitalized or shortened

### ISSUE THREAD

**Issue by BlueCrystal** [IanMitchell/ARX-7#140]
So it appears that there's an issue when someone does .blame boku dake and .blame Boku Dake. Results should be returned regardless of capitalization or if only part of the name is used

<pwg> .blame boku dake 
<Belfiore> Unknown Show boku dake 
<pwg> .blame Boku Dake ga Inai Machi
<Belfiore> Ep 1 of Boku Dake ga Inai Machi is at Translator Check as of a day ago. [​TL ​TLC ​ENC ​ED ​TI ​TS ​QC]
<Aoi-chan> .blame boku dake
<Belfiore> Unknown Show boku dake
<Aoi-chan> .blame Boku Dake
<Belfiore> Unknown Show Boku Dake

**Comment by IanMitchell** [comment]
Mostly it's the shortened issue, which is being tracked here: IanMitchell/Showtimes#8

The search for show's already is case insensitive :smile:
