### ISSUE TITLE
Edge case?

### ISSUE THREAD

**Issue by Fyurie** [IanMitchell/ARX-7#142]
[09/01][23:11] <&duplex> .done BokuMachi !encode
[09/01][23:11] <%Belfiore> Invalid position.
[09/01][23:11] <%Belfiore> Please specify position
[09/01][23:11] <%Belfiore> Updated Boku Dake ga Inai Machi. Ep 1 of Boku Dake ga Inai Machi is at Editor as of a few seconds ago.

I omitted the position status bit coz color-codes don't copy over.

**Comment by IanMitchell** [comment]
Basically it went through all three responses?

**Comment by Fyurie** [comment]
Yeah that's the exact output for the one command, from what I could see.

**Comment by IanMitchell** [comment]
This is the only one I don't know offhand; will take a bit of digging. Did it get updated correctly?

**Comment by Fyurie** [comment]
Yeah, I even tested it right after with my own undone and done for encode, and it behaved normally. It was literally just this one message.

**Comment by IanMitchell** [comment]
Can you pastebin logs for like the +/- 20 messages earlier, and DM them to me?

**Comment by Fyurie** [comment]
Done.

**Comment by IanMitchell** [comment]
I think duplex is right; it was a lag issue. Logs are 50mb or so, but I suspect it was the bot rather than Showtimes.

**Comment by IanMitchell** [comment]
Actually, leaving this open due to the time gap.

**Comment by IanMitchell** [comment]
Looks like it was a ARX-7 server thing
