### ISSUE TITLE
Showtimes Time (Moment) Grammar Issues

### ISSUE THREAD

**Issue by IanMitchell** [IanMitchell/ARX-7#145]
> <&Desch>	.blame aokana
> <%Belfiore>	Ep 1 of Ao no Kanata no Four Rhythm will air in 4 hours ago. [​TL ​TLC ​ENC ​ED ​TI ​TS ​QC]

**Comment by puddi** [comment]
language framework ; )

**Comment by IanMitchell** [comment]
@fyurie is so cold

><&Fyurie>	>[11/01][16:07] <%Belfiore> Ep 1 of Ao no Kanata no Four Rhythm will air in in an hour. [​TL ​TLC ​ENC ​ED ​TI ​TS ​QC]
> <&Fyurie>	did anyone point thato ne out to you yet

**Comment by IanMitchell** [comment]
Pretty sure I fixed this a while ago
