### ISSUE TITLE
Add Staff Time Command

### ISSUE THREAD

**Issue by IanMitchell** [IanMitchell/ARX-7#148]
> <&skiddiks> make a command like
> <&skiddiks> .time Desch
> <%Belfiore> skiddiks: Wed Jan 13 2016 03:40:32 GMT+0000 (UTC)
> <&skiddiks> that spits out the current time

**Comment by IanMitchell** [comment]
@skiddiks what do you think about an alarm function? Something like, `.alarm add <user> <time>` so the bot would ping you at that time for that user's timezone?

**Comment by skiddiks** [comment]
more features doesn't hurt anyone

**Comment by IanMitchell** [comment]
Except for me

Gotta finish those automated tests
