### ISSUE TITLE
Colors aren't copied for the same script

### ISSUE THREAD

**Issue by BlueCrystal** [IanMitchell/ARX-7#153]
It seems as though colors aren't copied for the same script. Colors do work with the showtimes portion of the bot, however. Screenshot should explain pretty well: https://dl.dropboxusercontent.com/u/81636/hexchat_2016-01-18_01-17-51.png

**Comment by IanMitchell** [comment]
Yup. Colors and other special symbols are stripped out; this is to prevent blacklist evasion. Not something we'll change, probably
