### ISSUE TITLE
Github Commit Spam Functionality

### ISSUE THREAD

**Issue by BlueCrystal** [IanMitchell/ARX-7#154]
Add a script or functionality that can be enabled/set on a per-channel basis for sending new commits along with a link to the commit, the name of the tree (if thats the right name) the commit is a part of, the commit ID, and whatever information that may be relevant for spamming up the channel. This would be similar to github's gitbot. The main reason for requesting this is that the git bot connects to the network, joins the channel, spams the commit, then parts. If there's already a bot in the channel, the bot may as well do this instead of using Github's. This is the information that's spammed to the channel:
`<GJM-GitBot> [gjmbatchscripts] GITUSERNAME pushed 1 new commit to TREENAME: LINKTOCOMMIT`
`<GJM-GitBot> PROJECTNAME/TREENAME COMMITID GITUSERNAME: COMMITDESCRIPTION`

And an example:
`<GJM-GitBot> [gjmbatchscripts] Fyurie pushed 1 new commit to master: https://github.com/Fyurie/gjmbatchscripts/commit/49e8e4c5e3df3d8fc7e923f035fbfa13eb6134c8`
`<GJM-GitBot> gjmbatchscripts/master 49e8e4c Fyurie: Haruchika (TV): 02 [Dialogue]...`
(Link to example spam: https://dl.dropboxusercontent.com/u/81636/hexchat_2016-01-18_05-25-41.png)

The URL could probably be shortened using goo.gl or is.gd or another url shortening service to cut down on the length of the message and fit everything in to one line. There is color formatting to the message as well. Due to the computer I'm using I can't screenshot it but this is what it appears to be:

Brackets around the project name are white.
PROJECTNAME is a lighter purple/magenta/whatever (Color code 13)
GITUSERNAME is light gray. (Color code 15)
The number 1 (which probably changes based on the number of commits) is bold.
TREENAME is a darker purple (Color code 6)

**Comment by IanMitchell** [comment]
Would have to probably enable this with a github hook, which would mean enabling a web endpoint for the bot. Alternatively, we could ping GitHub every minute or so, but then there would be a delay

**Comment by Fyurie** [comment]
I mean, only bother if it isn't a pain in the ass, I'm using GitHub's integrated service right now so I'm fine.

**Comment by IanMitchell** [comment]
Yeah, I'd rather focus on other features I think, especially since this already exists, and would require a lot of additional resources for the bot
