### ISSUE TITLE
Add a .airing command

### ISSUE THREAD

**Issue by Fyurie** [IanMitchell/ARX-7#157]
Similar in concept to the .nextep command, this would print the air-times for the next eps for all current season shows, each in a newline.

Syntax is simply .airing.

Output formatting is something along the lines of: "Episode [x] of [show] will air in [ETA].", with each result in a newline.

This is a staff-only command as it's potentially spammy on busy seasons, and is mainly for project management purposes.

**Comment by IanMitchell** [comment]
Are you sure you want newlines? I could try to format it a little more clearly, something like:

"Show 1 [3 days], Show 2 [2 days], Show 3 [4 days]" or something similar. Using an alias instead of their full name could help there too

**Comment by Fyurie** [comment]
That works until you print shows like haruchika and something like oregairu on the same line, for example. They both have shit-long titles that are painful to read on their own, let alone together.

**Comment by IanMitchell** [comment]
Yeah, which is why I thought maybe aliases could be an alternative. Seems like full names wouldn't be a requirement here?

**Comment by Fyurie** [comment]
I guess that works, so long as we have aliases, but for the amount of shows we currently do, newlining just seemed tidier and easier to read.

**Comment by IanMitchell** [comment]
I have deep misgivings about making the bot put anything on 2+ lines haha, if I can keep it to one line it'd be much preferable.

@kunaldes, random IRC question for you - did a cursory search, and didn't find anything on message length. Does IRC handle automatically breaking messages that are over X characters into different lines, or is that an IRC client thing?

Basically, do I need to add a method to break up messages in the bot or does the server do that?

**Comment by Fyurie** [comment]
If servrhe gets away with it, I'm sure Belfiore can. :P

**Comment by IanMitchell** [comment]
It looks like Servrhe only prints one show; is there a cap on what it displays? Maybe all shows that air that day?

**Comment by Fyurie** [comment]
Yeah, it prints within the coming 24 hours.

I was hoping for an expanded version that would output all of the group's projects for management purposes.

**Comment by IanMitchell** [comment]
Makes sense, yeah. I agree it'd be better to output the entire week's results

**Comment by kunaldes** [comment]
There is a character limit per line, but I'm not sure whether it's client
or server that does the line breaking. I suspect it's the client.

**Comment by IanMitchell** [comment]
> Desch:	.lorem
> ARX-7:	Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lo
> ARX-7:	recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

Looks like the bot linebreaks automatically!

**Comment by kunaldes** [comment]
That line break looks like it cut off a few words

**Comment by IanMitchell** [comment]
Oh, snap. You're right. Hm.
