### ISSUE TITLE
Tweet feature

### ISSUE THREAD

**Issue by Kyhz** [IanMitchell/ARX-7#186]
I am lazy. This is probably going to be horribly abused.
`.tweet @kunaldes are we going to the Lotus Juice concert?` 
becomes
`@kunaldes are we going to the Lotus Juice concert? -Kyhz`

**Comment by kunaldes** [comment]
lmao

**Comment by IanMitchell** [comment]
Kinda relates to #73 heheh

**Comment by Kyhz** [comment]
Glad we both agree this is a terrible idea. Let's do it.

**Comment by IanMitchell** [comment]
:+1:

**Comment by IanMitchell** [comment]
The twitter account @ commiedevs is available lol

**Comment by IanMitchell** [comment]
This would be so bad
