### ISSUE TITLE
Soundcloud Support

### ISSUE THREAD

**Issue by IanMitchell** [IanMitchell/ARX-7#23]
Vlvt requested Soundcloud support, similar to how YouTube works

**Comment by Dium** [comment]
#include <iostream>
using namespace std;
int main()
{

cout >> "don't do it mang" >> endl;
system("pause");
return 0;

}

**Comment by IanMitchell** [comment]
Not a ton of these links are posted; would be happy to accept a PR, but not gonna do it myself
