### ISSUE TITLE
[Twitter] Entities display as the spelled out item instead of the character itself

### ISSUE THREAD

**Issue by BlueCrystal** [IanMitchell/ARX-7#25]
It seems that characters like <, >, &, and so on will display as their respective entity names (or whatever they're called), &gt;, &lt;, &amp;. Ideally it would just display the characters instead of taking up the space.

For example, the tweet https://twitter.com/StockTwits/status/612616851269488640 displays as the following:

<Belfiore> [Twitter]: 15 patterns in technical analysis and how they look.  Print this out and hang it -&gt; http://t.co/scZXLVMbdL $SPY http://t.co/VE30iFWL6n | By StockTwits (@StockTwits)
<CaeX> theres the one with the candles

**Comment by IanMitchell** [comment]
Yeah, @kunaldes found that out a while ago - planning to fix that as part of #24 and #16 I believe
