### ISSUE TITLE
Identifying to Nickserv should occur before joining channels

### ISSUE THREAD

**Issue by BlueCrystal** [IanMitchell/ARX-7#37]
It seems that the bot isn't identifying to nickserv and then joining the channels defined in the config. It's either joining too quickly and exposing the host or it's joining the channels first and then identify to nickserv. Currently, this is what occurs:

* Belfiore (~kimi@Rizon-2A82E1D4.com) has joined
* Athena gives channel half-operator status to Belfiore

The host reflected should be "bots.on.bots".

**Comment by kunaldes** [comment]
Channel joining is part of the framework, but identifying is done as a
callback.

Should be fairly straightforward to move channel joining to the callback.

**Comment by IanMitchell** [comment]
Yup, that's the plan. I can also join +k channels correctly on the first pass (will require a slight rewrite of the autorejoin logic). 

Aoi-chan just loves making me reinvent the wheel :cry:
