### ISSUE TITLE
Add SSL Support to the Config

### ISSUE THREAD

**Issue by BlueCrystal** [IanMitchell/ARX-7#47]
Ideally, SSL Support should be added to the bot. Most decent IRC servers support SSL connections, typically on port 6697 or 9999, however some use different ports. Ideally you could just add something to config.json for a "ssl": "true/false". Either that or make it detect on the server line in config.json whether there is a colon and a port, for example irc.rizon.net:6667 (non-ssl) or irc.rizon.net:+6697 (ssl). It may be better to just have them both separate.

**Comment by IanMitchell** [comment]
Are certain ports pointed to SSL/non-SSL? Trying to figure out if we need to add both port support and an SSL flag, or if we can infer SSL somehow.

**Comment by kunaldes** [comment]
It varies from server to server. Like aoi mentioned, it's *generally* 6697
or 9999 but there's no way of knowing ahead of time. You'd probably get 99%
of the cases by having 6697 and 9999 mean ssl, and all other ports non-ssl,
but you could always get an oddly configured server or bouncer.

**Comment by IanMitchell** [comment]
Gotcha. And the plus in `+xxxx` port bit is required for SSL, left out for non-SSL?
