### ISSUE TITLE
Permit Connections to ZNC Bouncers

### ISSUE THREAD

**Issue by BlueCrystal** [IanMitchell/ARX-7#49]
For uptime and other reasons, it would be nice to be able to be able to connect the bot to a user on a bouncer. The general way this works is that you have a ZNC instance running on a server to keep the user online even if the user isn't actually connected in an IRC client. The general process for this is as follows:

/server whateverdomain.com:xxxx or /server whateverdomain.com:+xxxy (for SSL).
Once you've connected to the server you'll get the following:
*** You need to send your password. Configure your client to send a server password.
*** To connect now, you can use /quote PASS <username>:<password>, or /quote PASS <username>/<network>:<password> to connect to a specific network.

At that point, you can provide what is requested. You would reply by sending the server the following:
/quote pass username:password
OR
/quote pass username/network:password

Once it has done that, it will join all the channels and be connected. I imagine this will be best as a config option of a ZNC yes/no option, a znc username option, a znc network option (i personally don't use ZNC in that fashion), and a znc password option. If there is no ZNC Network, then just put the znc username and password together to get username:password.

**Comment by IanMitchell** [comment]
Does the ZNC handle joining channels, or is that done the standard way with a `/cs join #channel` command?

**Comment by kunaldes** [comment]
iirc you just send znc `/join #channel` and it'll join the channel.

This working depends on the bot supporting server-sent `JOIN`s. 

Also random tidbit, `/quote` is how many irc clients send raw messages, so the over the wire message would be `pass username:password`, while a standard message to a channel is something like `PRIVMSG #channel :<message>` (if i'm not mistaken).

My knowledge of the irc protocol is pretty cursory so definitely do some more research before implementing this.

**Comment by IanMitchell** [comment]
Gonna need to work with you a bit for this one, @BlueCrystal

**Comment by IanMitchell** [comment]
So when you connect to the ZNC, how does it decide what server to go through? Is that a user setting, or a server setting? (ie, you connect to the znc, then do you connect to rizon or does the server know to connect to rizon for you?)

**Comment by IanMitchell** [comment]
Hm, ok. Have this setup, but node-irc requires a target to send a message to, unless you construct a raw message object. This might get a little nasty.

**Comment by IanMitchell** [comment]
> [20:57:36]  <Steaki>	Desch, the solution is to listen for raw server PING/PONG events and attempt reconnect if its been >10 mins since last event

**Comment by IanMitchell** [comment]
Closing this, it'd be too painful to implement. Not worth it
