### ISSUE TITLE
Permit Invalid SSL Certificates

### ISSUE THREAD

**Issue by BlueCrystal** [IanMitchell/ARX-7#50]
Due to self-signing issues with IRC servers and ZNC bouncers, it is often necessary to permit invalid SSL certificates or Unsigned certificates. Hexchat, for example, has an option in the server list to accept invalid SSL certificates. For security reasons it should be a setting, but the need for the feature is there.

**Comment by IanMitchell** [comment]
Would this correspond to a selfSigned certificate, as defined here? https://node-irc.readthedocs.org/en/latest/API.html
