### ISSUE TITLE
Commands do not respond in three or more channels based on their place in the config.

### ISSUE THREAD

**Issue by BlueCrystal** [IanMitchell/ARX-7#52]
On the little bit of testing I did, it appears that the bot does not respond to commands based on the position of the channel in the config file. Everything below the second channel name entry won't respond to any of the listed commands. The bot will join the channels just fine, however. Example below:

```
  "channels": [
    {
      "name": "#aoi-chan",
      "key": null,
      "plugins": [
        "choose",
        "reply",
        "order",
        "twitter",
        "youtube",
        "time"
      ]
    },
    {
      "name": "#commie-subs",
      "key": null,
      "plugins": [
        "choose",
        "reply",
        "imgur",
        "order",
        "twitter",
        "youtube"
      ]
    },
    {
      "name": "#fffpeeps",
      "key": null,
      "plugins": [
        "choose",
        "reply",
        "imgur",
        "order",
        "twitter",
        "youtube"
      ]
    },
    {
      "name": "#horriblesubs",
      "key": null,
      "plugins": [
        "choose",
        "reply",
        "imgur",
        "order",
        "twitter",
        "youtube"
      ]
    },
    {
      "name": "#gundam",
      "key": null,
      "plugins": [
        "choose",
        "reply",
        "imgur",
        "order",
        "twitter",
        "youtube"
      ]
    }
  ],
```

**Comment by IanMitchell** [comment]
I can't seem to duplicate this - are you on the latest version of the app? How are you running the bot?

**Comment by BlueCrystal** [comment]
Using the latest update, this appears to impact channels in alphabetical order. For example, the bot joins #nisekoi, #commie-subs, #aoi-chan, #fffpeeps, #horriblesubs, and #gundam, yet the commands only work in #aoi-chan and #commie-subs.

**Comment by IanMitchell** [comment]
Still not able to repro. Will keep trying

**Comment by IanMitchell** [comment]
From Steaki: https://github.com/martynsmith/node-irc/issues/249

Might want to look into the message handler

**Comment by IanMitchell** [comment]
@BlueCrystal are the channels that break something like `#Nisekoi` (capitalized) on the server? Or is it `#nisekoi`?

**Comment by kunaldes** [comment]
It's `#Nisekoi` `#FFFpeeps` and `#HorribleSubs`

Definitely looking like the issue steaki mentioned.

**Comment by IanMitchell** [comment]
Yup. Glad we figured it out :smile: 

This will be a thorny issue, I'll start looking at ways around it... might require the config to have the exact channel name, unless we can join the channel / update our internal configuration with the "proper" name.

**Comment by IanMitchell** [comment]
Wasn't that bad :smiley: will be fixed in next release
