### ISSUE TITLE
Add a check on the bot start to validate that channels are properly formatted

### ISSUE THREAD

**Issue by BlueCrystal** [IanMitchell/ARX-7#56]
When the bot starts, it's possible for the name field in config.json to not be a properly formatted channel. You can essentially have just "nisekoi" instead of "#nisekoi". Of course, the bot should also allow to be launched with double hashes for those odd channels on freenode like ##freebsd or something.

**Comment by IanMitchell** [comment]
It currently checks and fixes everything except a double hash - if you do a double hash, it should still work. It just can't really know if a single hash was supposed to be a double :smile:
