### ISSUE TITLE
Feature to limit the number of lines spammed per second

### ISSUE THREAD

**Issue by BlueCrystal** [IanMitchell/ARX-7#69]
It would be nice to have a feature added so the user can specify how many lines can be flooded to the server per second before it gets excess flooded out. Apparently Rizon has a limit at 1 line/500ms global limit, but I'm not sure if thats a network limit or a server limit, so being able to set the ratelimiting globally would be nice so it can impact all bot responses.

**Comment by IanMitchell** [comment]
There's a config option for rate limiting - I'll mess around with flagging that and see what happens
