### ISSUE TITLE
Username Permissions

### ISSUE THREAD

**Issue by IanMitchell** [IanMitchell/ARX-7#76]
We should try to move away from passwords and support whitelisted identified names for admin commands. `node-irc` doesn't support this; we'll have to figure out a way to do this ourselves.

**Comment by IanMitchell** [comment]
> [09:31:55]  <GrygrFlzr>	/whois Fyurie
> [09:32:02]  <GrygrFlzr>	returns identified status

**Comment by IanMitchell** [comment]
> GrygrFlzr:	Desch, you can also use /mode GrygrFlzr and check for the +r flag

**Comment by kunaldes** [comment]
Doing a /msg nickserv status [nick] gives you an integer you can check.

**Comment by IanMitchell** [comment]
Hm, got 3 when I ran it on @fyurie - any ideas what numbers correspond to what?

**Comment by IanMitchell** [comment]
> [13:58:08] -NickServ-	    0 - no such user online or nickname not registered
> [13:58:08] -NickServ-	    1 - user not recognized as nickname's owner
> [13:58:08] -NickServ-	    2 - user recognized as owner via access list only
> [13:58:08] -NickServ-	    3 - user recognized as owner via password identification

**Comment by kunaldes** [comment]
For reference, the access list is a list of ip addresses or hostnames that
are allowed to use the nick without inputting a password.

**Comment by IanMitchell** [comment]
So this one is gonna be a little tricky. Current idea:

Have a method called `isAuthenticated(username)` that returns a promise. In that method, it sends a message to NickServ. The tricky part is NickServ replies via NOTICE, so we're gonna need to wait until an event is triggered here. Once we get the response, it's easy enough; parse the result text, if it's 2+ resolve true, else reject false. 

I'm not quite sure how to get past the hangup though. Any ideas @kunaldes? I feel like it should be easy and I'm making things too hard by thinking about callbacks, events, and promises.

**Comment by puddi** [comment]
wait, what's the problem with the hangup?

**Comment by IanMitchell** [comment]
Kinda figured it out with Jukey's help :D. PR submitted for it

**Comment by IanMitchell** [comment]
Merged
