### ISSUE TITLE
Automatic Updates

### ISSUE THREAD

**Issue by IanMitchell** [IanMitchell/ARX-7#79]
It'd be fun to have an option where the bot could auto-update itself. Not sure how entirely feasible it is, but it's worth looking into!

**Comment by puddi** [comment]
You have to do it outside the process for ARX-7, obviously.

Here's an idea:

set a cron that calls another script that checks to see the latest release from this repo (via the github api). if it is, shut down the ARX process with a specific flag (to trigger some kind of 'Shutting down for updates' message), fetch the latest release, unpack it, and replace the src files in the directory ARX is in on your server.

**Comment by IanMitchell** [comment]
Really not necessary

**Comment by puddi** [comment]
I can't believe you would just close this issue without letting everyone deliberate on the suggestion. Rude to the original submitter.
