### ISSUE TITLE
User Specific Ignore Feature

### ISSUE THREAD

**Issue by BlueCrystal** [IanMitchell/ARX-7#80]
It would be nice to be able to ignore specific people like chronic spammers, people who flood the channel, and nbk. :)

**Comment by IanMitchell** [comment]
rotn?

**Comment by puddi** [comment]
If you're redoing the entire user permissions thing ala #76, then whitelisting/blacklisting based off of host/name wouldn't be that hard.

**Comment by IanMitchell** [comment]
Something like this would be really easy to avoid; feels like a blackhole for development purposes. I can ban nicks, but then they nick change. I ban hosts, they just modify those. I'd rather it be on the channel to enforce a no-spam rule if necessary, and for the admins to be in charge of moderation.

**Comment by puddi** [comment]
> I can ban nicks, but then they nick change. I ban hosts, they just modify those.

yes? every irc banning system is based off of hosts and nicks. there's nothing special about it.

if people are ban-evading to bypass the blacklist, then they're ban-evading within the channel, and that's something channel %+s can and should ban for.

**Comment by puddi** [comment]
The "there is no perfect system, therefore there is no value" logic is inherently flawed.

**Comment by IanMitchell** [comment]
I'm not saying there's no value in an ignore feature, I just don't see a clear use case for this that justifies the amount of work. I'd rather rely on channel operators to enforce rules and ban spammers than have that logic built into the bot itself; it feels like I'd be reimplementing the wheel. 

When would the bot ignore someone when they wouldn't just be banned outright?

**Comment by IanMitchell** [comment]
Alternatively, why not just have the bot nick ignore said user? I think there are several ways to leverage IRC to achieve this functionality rather than coding it into the bot

**Comment by IanMitchell** [comment]
I could add an admin query command to alias IRC's ignore command I guess, but that's about as far as I want to go

**Comment by puddi** [comment]
ignores are irc client functionality. from my understanding, node-irc establishes a direct connection w/ the server, so you're sol there

**Comment by IanMitchell** [comment]
Hmm, ok
