### ISSUE TITLE
Add Color Support

### ISSUE THREAD

**Issue by IanMitchell** [IanMitchell/ARX-7#96]
We removed it at one point (https://github.com/IanMitchell/ARX-7/blob/master/src/bot.js#L14) but not quite sure why - something to do with blacklists or an error in logic I think. I'll take a look and see if I can figure out what it was.

**Comment by kunaldes** [comment]
#44

**Comment by IanMitchell** [comment]
Oh, right. Strips more than colors, thanks Jukey!
